// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201609120807416_Fixed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201609120807416_Fixed2));
        
        string IMigrationMetadata.Id
        {
            get { return "201609120812431_201609120807416_Fixed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
