// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201609120807416_Fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201609120807416_Fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201609120811355_201609120807416_Fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
